#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#
# The configuration is split into several small files
# to define the configuration for complex backends.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://symfony.com/doc/current/bundles/EasyAdminBundle/index.html
#
imports:
- { resource: easy_admin/ }
