fm_elfinder:
  assets_path: '/bundles/elfinder'
  instances:
    default:
      locale:           "%locale%"
      editor:           ckeditor
      fullscreen:       false
      theme:            smoothness
      include_assets:   true
      connector:
        debug:        false
        roots:
          uploads:
            driver:           LocalFileSystem
            path:             build/uploads/images/article
            upload_allow:     ['image/png', 'image/jpg', 'image/jpeg', 'image/gif', 'audio/mpeg', 'video/mp4', 'video/webm', 'application/pdf']
            upload_deny:      ['all']
            upload_max_size:  2M
