twig:
    default_path: '%kernel.project_dir%/templates'
    #form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        product_prefix: "%app.path.product_images%"
        category_prefix: "%app.path.category_images%"
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
#    paths:
#        '%kernel.project_dir%/vendor/helios-ag/fm-tinymce-bundle/src/Resources/views': "FMTinyMCEBundle"