easy_admin:
  entities:
    Article:
      class: App\Entity\Article
      list:
        title: title.article.list
        fields:
        - { property: 'id',               label: label.id }
        - { property: 'enabled',          label: label.enabled }
        - { property: 'articleCategory',  label: label.article.type }
        - { property: 'title',            label: label.title }
        - { property: 'updatedAt',        label: label.updated_at }
        - { property: 'createdAt',        label: label.created_at }
      new:
        title: title.article.new
        fields:
        - { property: 'enabled',        label: label.enabled }
        - { property: 'articleCategory',label: label.article.type }
        - { property: 'title',          label: label.title }
        - { property: 'contains',       label: label.contains, type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
      edit:
        title: title.article.edit
        fields:
        - { property: 'enabled',        label: label.enabled }
        - { property: 'articleCategory',label: label.article.type }
        - { property: 'title',          label: label.title }
        - { property: 'contains',       label: label.contains, type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
