easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
        title: title.category.list
        fields:
        - { property: 'id',         label: label.id }
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'image',      label: label.image,   type: 'image', template: 'common\vich_uploader_image.html.twig' }
        sort: ['name', 'ASC']
        actions: ['show', 'edit', 'delete']
      form:
        fields:
        - { type: 'group',              label: group.common.information, icon: 'wrench' }
        - { property: 'enabled',        label: label.enabled }
        - { property: 'name',           label: label.name }
        - { type: 'group',              label: group.common.image, icon: 'image' }
        - { property: 'imageFile',      label: label.image, type: 'vich_image', type_options: { required: false } }
        - { type: 'group',              label: group.common.relations, icon: 'link' }
        - { property: 'subcategories',  label: label.sub_category }
        - { property: 'products',       label: label.products }
      new:
        title: title.category.new
      edit:
        title: title.category.edit
      show:
        title: title.category.show
        fields:
        - { property: 'id',             label: label.id }
        - { property: 'enabled',        label: label.enabled }
        - { property: 'name',           label: label.name }
        - { property: 'image',          label: label.image, type: 'image', base_path: '%app.path.category_images%' }
        - { property: 'subcategories',  label: label.sub_category }
        - { property: 'products',       label: label.products }