easy_admin:
  entities:
    EnterpriseDetails:
      disabled_actions: ['delete', 'new']
      class: App\Entity\EnterpriseDetails
      list:
        title: title.enterprise.list
        fields:
        - { property: 'name'      , label: label.name }
        - { property: 'address'   , label: label.address }
        - { property: 'codePostal', label: label.code_postal }
        - { property: 'city'      , label: label.city }
        - { property: 'telephone' , label: label.cellphone }
        - { property: 'email'  ,    label: label.email }
      show:
        title: title.enterprise.show
        fields:
        - { property: 'name'      , label: label.name }
        - { property: 'address'   , label: label.address }
        - { property: 'codePostal', label: label.code_postal }
        - { property: 'city'      , label: label.city }
        - { property: 'telephone' , label: label.cellphone }
        - { property: 'email'  ,    label: label.email }
      edit:
        title: title.enterprise.edit
        fields:
        - { property: 'name'      , label: label.name }
        - { property: 'address'   , label: label.address }
        - { property: 'codePostal', label: label.code_postal }
        - { property: 'city'      , label: label.city }
        - { property: 'telephone' , label: label.cellphone }
        - { property: 'email'  ,    label: label.email }
