easy_admin:
  entities:
    Product:
      class: App\Entity\Product
      show:
        title: '%%entity_label%% (#%%entity_id%%)'
      list:
        title: title.product.list
        fields:
        - { property: 'id',         label: label.id }
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'quantity',   label: label.quantity }
        - { property: 'image',      label: label.image,             type: 'image', base_path: '%app.path.product_images%' }
        - { property: 'price',      label: label.price }
        - { property: 'refundable', label: label.refundable }
        - { property: 'category',   label: label.category }
        - { property: 'subcategory',label: label.sub_category }
        - { property: 'packaging',  label: label.packaging }
      form:
        fields:
        - { type: 'group',          label: group.common.information,icon: 'wrench' }
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'price',      label: label.price }
        - { property: 'taxRate',    label: label.tax_rate,          type_options: { required: true } }
        - { property: 'description',label: label.description,       type: 'FOS\CKEditorBundle\Form\Type\CKEditorType'  }
        - { type: 'group',          label: group.common.other,      icon: 'info' }
        - { property: 'refundable', label: label.refundable }
        - { property: 'packaging',  label: label.packaging }
        - { property: 'quantity',   label: label.quantity }
        - { type: 'group',          label: group.product.order,     icon: 'shopping-cart' }
        - { property: 'isPurchase', label: label.is_purchase }
        - { type: 'group',          label: group.common.image,      icon: 'image' }
        - { property: 'imageFile',  label: label.image,             type: 'vich_image', type_options: { required: true } }
        - { type: 'group',          label: group.common.relations,  icon: 'link' }
        - { property: 'category',   label: label.category,          type_options: { required: true } }
        - { property: 'subcategory',label: label.sub_category }
      new:
        title: title.product.new
      edit:
        title: title.product.edit