easy_admin:
  entities:
    Product:
      class: App\Entity\Product
      show:
        title: '%%entity_label%% (#%%entity_id%%)'
      list:
        title: title.product.list
        fields:
        - { property: 'id',         label: label.id }
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'quantity',   label: label.quantity }
        - { property: 'description',label: label.description }
        - { property: 'image',      label: label.image, type: 'image', base_path: '%app.path.product_images%' }
        - { property: 'createdAt',  label: label.created_at, format: 'j/m/Y' }
        - { property: 'price',      label: label.price }
        - { property: 'refundable', label: label.refundable }
        - { property: 'category',   label: label.category }
        - { property: 'subcategory',label: label.sub_category }
        - { property: 'packaging',  label: label.packaging }
      new:
        title: title.product.new
        fields:
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'quantity',   label: label.quantity }
        - { property: 'price',      label: label.price }
        - { property: 'refundable', label: label.refundable }
        - { property: 'taxRate',    label: label.tax_rate }
        - { property: 'imageFile',  label: label.image, type: 'vich_image', type_options: { required: true } }
        - { property: 'category',   label: label.category }
        - { property: 'subcategory',label: label.sub_category }
        - { property: 'packaging',  label: label.packaging }
        - { property: 'description',label: label.description, type: 'ckeditor' }
      edit:
        title: title.product.edit
        fields:
        - { property: 'enabled',    label: label.enabled }
        - { property: 'name',       label: label.name }
        - { property: 'quantity',   label: label.quantity }
        - { property: 'price',      label: label.price }
        - { property: 'refundable', label: label.refundable }
        - { property: 'taxRate',    label: label.tax_rate }
        - { property: 'imageFile',  label: label.image, type: 'vich_image', type_options: { required: true } }
        - { property: 'category',   label: label.category }
        - { property: 'subcategory',label: label.sub_category }
        - { property: 'packaging',  label: label.packaging }
        - { property: 'description',label: label.description, type: 'ckeditor' }
