easy_admin:
  entities:
    TaxRate:
      class: App\Entity\TaxRate
      list:
        title: title.vat.list
        fields:
        - { property: 'id',               label: label.id }
        - { property: 'rate',             label: label.rate }
      form:
        fields:
        - { property: 'rate',             label: label.rate }
      new:
        title: title.vat.new
      edit:
        title: title.vat.edit